// Autogenerated from Pigeon (v26.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsCertificateFetcherApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsCertificateFetcherApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsCertificateFetcherApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashCertificateFetcherApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashCertificateFetcherApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashCertificateFetcherApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Result of a synchronous snapshot read; Dart polls until [success] or [failed].
enum CertificateChainSnapshotStatus: Int {
  /// Native fetch in flight or not yet started for this key.
  case pending = 0
  /// Terminal success; [certificates] is non-empty (DER base64).
  case success = 1
  /// Terminal failure (timeout, empty chain, etc.); [certificates] is empty.
  case failed = 2
}

/// Cache / single-flight key (no per-call id).
///
/// Generated class from Pigeon that represents data sent in messages.
struct CertificateChainKey: Hashable {
  var host: String
  var port: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CertificateChainKey? {
    let host = pigeonVar_list[0] as! String
    let port = pigeonVar_list[1] as! Int64

    return CertificateChainKey(
      host: host,
      port: port
    )
  }
  func toList() -> [Any?] {
    return [
      host,
      port,
    ]
  }
  static func == (lhs: CertificateChainKey, rhs: CertificateChainKey) -> Bool {
    return deepEqualsCertificateFetcherApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCertificateFetcherApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CertificateChainSnapshot: Hashable {
  var status: CertificateChainSnapshotStatus
  /// DER, base64. Non-empty only when [status] == [CertificateChainSnapshotStatus.success].
  var certificates: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CertificateChainSnapshot? {
    let status = pigeonVar_list[0] as! CertificateChainSnapshotStatus
    let certificates = pigeonVar_list[1] as! [String]

    return CertificateChainSnapshot(
      status: status,
      certificates: certificates
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      certificates,
    ]
  }
  static func == (lhs: CertificateChainSnapshot, rhs: CertificateChainSnapshot) -> Bool {
    return deepEqualsCertificateFetcherApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCertificateFetcherApi(value: toList(), hasher: &hasher)
  }
}

private class CertificateFetcherApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CertificateChainSnapshotStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return CertificateChainKey.fromList(self.readValue() as! [Any?])
    case 131:
      return CertificateChainSnapshot.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CertificateFetcherApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CertificateChainSnapshotStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CertificateChainKey {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? CertificateChainSnapshot {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CertificateFetcherApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CertificateFetcherApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CertificateFetcherApiPigeonCodecWriter(data: data)
  }
}

class CertificateFetcherApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CertificateFetcherApiPigeonCodec(readerWriter: CertificateFetcherApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CertificateFetcherApi {
  /// Fast path: returns cached terminal state, [pending], or starts background fetch and returns [pending].
  func getCertificateChainSnapshot(key: CertificateChainKey) throws -> CertificateChainSnapshot
  /// Aborts in-flight fetch for [key] (e.g. when Dart stops polling early).
  func cancelCertificateChainForHost(key: CertificateChainKey) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CertificateFetcherApiSetup {
  static var codec: FlutterStandardMessageCodec { CertificateFetcherApiPigeonCodec.shared }
  /// Sets up an instance of `CertificateFetcherApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CertificateFetcherApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Fast path: returns cached terminal state, [pending], or starts background fetch and returns [pending].
    let getCertificateChainSnapshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personal_cloud_photos.CertificateFetcherApi.getCertificateChainSnapshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCertificateChainSnapshotChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! CertificateChainKey
        do {
          let result = try api.getCertificateChainSnapshot(key: keyArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCertificateChainSnapshotChannel.setMessageHandler(nil)
    }
    /// Aborts in-flight fetch for [key] (e.g. when Dart stops polling early).
    let cancelCertificateChainForHostChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personal_cloud_photos.CertificateFetcherApi.cancelCertificateChainForHost\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelCertificateChainForHostChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! CertificateChainKey
        do {
          try api.cancelCertificateChainForHost(key: keyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelCertificateChainForHostChannel.setMessageHandler(nil)
    }
  }
}
