
variables:
  # Usefull for fastlane
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  # Usefull to build Android & Web
  ARTIFLETTE_PROJECT_NAME: "homecloud-frontend"
  FULL_BUILD_URL: "${ARTIFACT_SERVER}/api/builds/${ARTIFLETTE_PROJECT_NAME}"
  DOCKER_IMAGE: ${DOCKER_REGISTRY_URL}/seagate/flutter-android:3.35
  PUB_CACHE: ${CI_PROJECT_DIR}/.pub-cache
  # Usefull to ignore some files in the license check
  EXTRA_IGNORE_LICENSE_RULES: '-ignore "lib/api/**" -ignore "lib/l10n/generated/**" -ignore "**/generated*" -ignore "**/Generated*"'

include:
  - project: ci/templates
    ref: main
    file:
      - stages.yml
      - .init-version.yml

default:
  before_script:
    - export PATH="$PATH":"${PUB_CACHE}/bin"
    - export BUILD_NAME="0.18.0.${CI_PIPELINE_ID}"
    - export BUILD_NUMBER="${CI_PIPELINE_ID}"
    - export ANDROID_APP_NAME="noveo-signin-android-${BUILD_TYPE}-${BUILD_VERSION}.apk"
    - export WEB_APP_NAME="noveo-signin-web-${BUILD_TYPE}-${BUILD_VERSION}.tar.gz"
  cache:  # Cache modules using lock file
    key:
      files:
        - pubspec.lock
    paths:
      - ${PUB_CACHE}

"🍎 Build iOS":
  stage: 📦 Build
  tags:
    - macos_flutter
  dependencies: []
  artifacts:
    expire_in: 1 week
    paths:
      - build/ios/archive/Runner.xcarchive
  script:
    - flutter build ipa --release --no-codesign --build-name ${BUILD_NAME} --build-number ${BUILD_NUMBER}
  only:
    - merge_requests
    - main
  allow_failure: true
  timeout: 5 minutes

"🍎 Deploy to TestFlight":
  stage: 🚀 Deploy
  tags:
    - macos_flutter
  dependencies: []
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
  script:  
    - ruby --version
    - gem install bundler
    - cd ios
    - bundle install
    - cd ..
    - flutter build ios --release --no-codesign
    - cd ios
    - bundle exec fastlane beta
  only:
     - tags

"🤖 Build Android":
  stage: 📦 Build
  image: ${DOCKER_IMAGE}
  script:
  script:
    # - flutter upgrade # Warning: update Flutter and could introduce breaking change....
    - flutter build apk --build-name ${BUILD_NAME} --build-number ${BUILD_NUMBER}
  artifacts:
    expire_in: 1 week
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
  only:
    - merge_requests
    - main
    - tags

"🌐 Build Web":
  stage: 📦 Build
  image: ${DOCKER_IMAGE}
  script:
    - flutter build web --build-name ${BUILD_NAME} --build-number ${BUILD_NUMBER}
  artifacts:
    expire_in: 1 week
    paths:
      - build/web
  only:
    - merge_requests
    - main
    - tags

"🤖🌐 Deploy to Artiflette":
  stage: 🚀 Deploy
  image: ${DOCKER_IMAGE}
  script:
    - "echo ${FULL_BUILD_URL}/${BUILD_TYPE}/${BUILD_VERSION}"
    - "echo ${ANDROID_APP_NAME}"
    - "echo ${WEB_APP_NAME}"
    - (cd build/web; tar -czf ../../${WEB_APP_NAME} *)
    - "curl --fail -XPOST ${FULL_BUILD_URL}/${BUILD_TYPE}/${BUILD_VERSION}"
    - "cp build/app/outputs/flutter-apk/app-release.apk ${ANDROID_APP_NAME}"
    - "curl --fail -v --upload-file ${ANDROID_APP_NAME} ${FULL_BUILD_URL}/${BUILD_TYPE}/${BUILD_VERSION}/upload/"
    - "curl --fail -v --upload-file ${WEB_APP_NAME} ${FULL_BUILD_URL}/${BUILD_TYPE}/${BUILD_VERSION}/upload/"
    - "curl -XPOST -H 'Content-Type: application/json' -d'{\"type\": \"build\", \"value\": \"success\", \"metadata\":{\"downloads\":[{\"name\":\"android\", \"match\":\".*apk$\"}, {\"name\":\"web\", \"match\":\".*tar.gz$\"}]}}' ${FULL_BUILD_URL}/${BUILD_TYPE}/${BUILD_VERSION}/statuses"
  only:
    - main
    - tags
    - merge_requests

# TODO  - flutter test