// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsNetworkMonitor(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsNetworkMonitor(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsNetworkMonitor(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashNetworkMonitor(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashNetworkMonitor(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashNetworkMonitor(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum NativeTransportType: Int {
  case wifi = 0
  case cellular = 1
  case ethernet = 2
  case vpn = 3
  case other = 4
}

/// OS-reported network status used by the network monitor for recovery and
/// toast decisions. A read-only side channel: it does not replace
/// [ConnectivityApi], which stays untouched for backup checks.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeNetworkStatus: Hashable {
  var hasTransport: Bool
  var transports: [NativeTransportType]
  /// Whether the OS considers the network to actually have internet access.
  /// Android: NET_CAPABILITY_VALIDATED (system-side captive portal / internet
  /// validation). iOS has no public equivalent, so it reports null when a
  /// route exists and false when there is no route at all.
  var internetValidated: Bool? = nil
  var isExpensive: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeNetworkStatus? {
    let hasTransport = pigeonVar_list[0] as! Bool
    let transports = pigeonVar_list[1] as! [NativeTransportType]
    let internetValidated: Bool? = nilOrValue(pigeonVar_list[2])
    let isExpensive = pigeonVar_list[3] as! Bool

    return NativeNetworkStatus(
      hasTransport: hasTransport,
      transports: transports,
      internetValidated: internetValidated,
      isExpensive: isExpensive
    )
  }
  func toList() -> [Any?] {
    return [
      hasTransport,
      transports,
      internetValidated,
      isExpensive,
    ]
  }
  static func == (lhs: NativeNetworkStatus, rhs: NativeNetworkStatus) -> Bool {
    return deepEqualsNetworkMonitor(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashNetworkMonitor(value: toList(), hasher: &hasher)
  }
}

private class NetworkMonitorPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeTransportType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return NativeNetworkStatus.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NetworkMonitorPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeTransportType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeNetworkStatus {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NetworkMonitorPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NetworkMonitorPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NetworkMonitorPigeonCodecWriter(data: data)
  }
}

class NetworkMonitorPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NetworkMonitorPigeonCodec(readerWriter: NetworkMonitorPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NetworkMonitorApi {
  func getCurrentStatus() throws -> NativeNetworkStatus
  func startObserving() throws
  func stopObserving() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NetworkMonitorApiSetup {
  static var codec: FlutterStandardMessageCodec { NetworkMonitorPigeonCodec.shared }
  /// Sets up an instance of `NetworkMonitorApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NetworkMonitorApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getCurrentStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personal_cloud_photos.NetworkMonitorApi.getCurrentStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCurrentStatusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCurrentStatus()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCurrentStatusChannel.setMessageHandler(nil)
    }
    let startObservingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personal_cloud_photos.NetworkMonitorApi.startObserving\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startObservingChannel.setMessageHandler { _, reply in
        do {
          try api.startObserving()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startObservingChannel.setMessageHandler(nil)
    }
    let stopObservingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personal_cloud_photos.NetworkMonitorApi.stopObserving\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopObservingChannel.setMessageHandler { _, reply in
        do {
          try api.stopObserving()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopObservingChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol NetworkMonitorEventsProtocol {
  func onStatusChanged(status statusArg: NativeNetworkStatus, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class NetworkMonitorEvents: NetworkMonitorEventsProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: NetworkMonitorPigeonCodec {
    return NetworkMonitorPigeonCodec.shared
  }
  func onStatusChanged(status statusArg: NativeNetworkStatus, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.personal_cloud_photos.NetworkMonitorEvents.onStatusChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
