// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.seagate.curator.stxphotos.android.core

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NetworkPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class ClientCertData (
  val data: ByteArray,
  val password: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ClientCertData {
      val data = pigeonVar_list[0] as ByteArray
      val password = pigeonVar_list[1] as String
      return ClientCertData(data, password)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      data,
      password,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ClientCertData) {
      return false
    }
    if (this === other) {
      return true
    }
    return NetworkPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ClientCertPrompt (
  val title: String,
  val message: String,
  val cancel: String,
  val confirm: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ClientCertPrompt {
      val title = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      val cancel = pigeonVar_list[2] as String
      val confirm = pigeonVar_list[3] as String
      return ClientCertPrompt(title, message, cancel, confirm)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      message,
      cancel,
      confirm,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ClientCertPrompt) {
      return false
    }
    if (this === other) {
      return true
    }
    return NetworkPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class HttpRequestData (
  val method: String,
  val url: String,
  val headers: Map<String, String>,
  val body: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HttpRequestData {
      val method = pigeonVar_list[0] as String
      val url = pigeonVar_list[1] as String
      val headers = pigeonVar_list[2] as Map<String, String>
      val body = pigeonVar_list[3] as ByteArray?
      return HttpRequestData(method, url, headers, body)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      method,
      url,
      headers,
      body,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is HttpRequestData) {
      return false
    }
    if (this === other) {
      return true
    }
    return NetworkPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class HttpResponseData (
  val statusCode: Long,
  val headers: Map<String, String>,
  val body: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HttpResponseData {
      val statusCode = pigeonVar_list[0] as Long
      val headers = pigeonVar_list[1] as Map<String, String>
      val body = pigeonVar_list[2] as ByteArray
      return HttpResponseData(statusCode, headers, body)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      statusCode,
      headers,
      body,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is HttpResponseData) {
      return false
    }
    if (this === other) {
      return true
    }
    return NetworkPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class NetworkPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ClientCertData.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ClientCertPrompt.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HttpRequestData.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HttpResponseData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ClientCertData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ClientCertPrompt -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is HttpRequestData -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is HttpResponseData -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NetworkApi {
  fun addCertificate(clientData: ClientCertData, callback: (Result<Unit>) -> Unit)
  fun selectCertificate(promptText: ClientCertPrompt, callback: (Result<Unit>) -> Unit)
  fun removeCertificate(callback: (Result<Unit>) -> Unit)
  fun hasCertificate(): Boolean
  fun getClientPointer(): Long
  fun setRequestHeaders(headers: Map<String, String>, serverUrls: List<String>, token: String?)
  /** Installs custom root CAs (DER, base64) for the shared native HTTP client. */
  fun configureCertificatePinning(rootCertificatesBase64: List<String>)
  /** Registers intermediate/trusted certs (DER, base64) for [host], excluding the leaf. */
  fun registerTrustedChain(host: String, chainCertificatesBase64: List<String>)
  fun unregisterTrustedChain(host: String)
  /**
   * Performs an HTTP request on the shared native client (iOS URLSession / Android OkHttp).
   *
   * Completion is handled entirely in native code so Dart does not register FFI
   * URLSession completion blocks (which can crash after timeouts).
   */
  fun sendHttpRequest(request: HttpRequestData, timeoutSeconds: Long, callback: (Result<HttpResponseData>) -> Unit)

  companion object {
    /** The codec used by NetworkApi. */
    val codec: MessageCodec<Any?> by lazy {
      NetworkPigeonCodec()
    }
    /** Sets up an instance of `NetworkApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NetworkApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.NetworkApi.addCertificate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientDataArg = args[0] as ClientCertData
            api.addCertificate(clientDataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NetworkPigeonUtils.wrapError(error))
              } else {
                reply.reply(NetworkPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.NetworkApi.selectCertificate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val promptTextArg = args[0] as ClientCertPrompt
            api.selectCertificate(promptTextArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NetworkPigeonUtils.wrapError(error))
              } else {
                reply.reply(NetworkPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.NetworkApi.removeCertificate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.removeCertificate{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NetworkPigeonUtils.wrapError(error))
              } else {
                reply.reply(NetworkPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.NetworkApi.hasCertificate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hasCertificate())
            } catch (exception: Throwable) {
              NetworkPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.NetworkApi.getClientPointer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getClientPointer())
            } catch (exception: Throwable) {
              NetworkPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.NetworkApi.setRequestHeaders$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val headersArg = args[0] as Map<String, String>
            val serverUrlsArg = args[1] as List<String>
            val tokenArg = args[2] as String?
            val wrapped: List<Any?> = try {
              api.setRequestHeaders(headersArg, serverUrlsArg, tokenArg)
              listOf(null)
            } catch (exception: Throwable) {
              NetworkPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.NetworkApi.configureCertificatePinning$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val rootCertificatesBase64Arg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              api.configureCertificatePinning(rootCertificatesBase64Arg)
              listOf(null)
            } catch (exception: Throwable) {
              NetworkPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.NetworkApi.registerTrustedChain$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val hostArg = args[0] as String
            val chainCertificatesBase64Arg = args[1] as List<String>
            val wrapped: List<Any?> = try {
              api.registerTrustedChain(hostArg, chainCertificatesBase64Arg)
              listOf(null)
            } catch (exception: Throwable) {
              NetworkPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.NetworkApi.unregisterTrustedChain$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val hostArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.unregisterTrustedChain(hostArg)
              listOf(null)
            } catch (exception: Throwable) {
              NetworkPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.NetworkApi.sendHttpRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as HttpRequestData
            val timeoutSecondsArg = args[1] as Long
            api.sendHttpRequest(requestArg, timeoutSecondsArg) { result: Result<HttpResponseData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NetworkPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NetworkPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
