// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.seagate.curator.stxphotos.android.certificate

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object CertificateFetcherPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Result of a synchronous snapshot read; Dart polls until [success] or [failed]. */
enum class CertificateChainSnapshotStatus(val raw: Int) {
  /** Native fetch in flight or not yet started for this key. */
  PENDING(0),
  /** Terminal success; [certificates] is non-empty (DER base64). */
  SUCCESS(1),
  /** Terminal failure (timeout, empty chain, etc.); [certificates] is empty. */
  FAILED(2);

  companion object {
    fun ofRaw(raw: Int): CertificateChainSnapshotStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Cache / single-flight key (no per-call id).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CertificateChainKey (
  val host: String,
  val port: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CertificateChainKey {
      val host = pigeonVar_list[0] as String
      val port = pigeonVar_list[1] as Long
      return CertificateChainKey(host, port)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      host,
      port,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CertificateChainKey) {
      return false
    }
    if (this === other) {
      return true
    }
    return CertificateFetcherPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CertificateChainSnapshot (
  val status: CertificateChainSnapshotStatus,
  /** DER, base64. Non-empty only when [status] == [CertificateChainSnapshotStatus.success]. */
  val certificates: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CertificateChainSnapshot {
      val status = pigeonVar_list[0] as CertificateChainSnapshotStatus
      val certificates = pigeonVar_list[1] as List<String>
      return CertificateChainSnapshot(status, certificates)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      certificates,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CertificateChainSnapshot) {
      return false
    }
    if (this === other) {
      return true
    }
    return CertificateFetcherPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class CertificateFetcherPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CertificateChainSnapshotStatus.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CertificateChainKey.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CertificateChainSnapshot.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CertificateChainSnapshotStatus -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is CertificateChainKey -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is CertificateChainSnapshot -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CertificateFetcherApi {
  /** Fast path: returns cached terminal state, [pending], or starts background fetch and returns [pending]. */
  fun getCertificateChainSnapshot(key: CertificateChainKey): CertificateChainSnapshot
  /** Aborts in-flight fetch for [key] (e.g. when Dart stops polling early). */
  fun cancelCertificateChainForHost(key: CertificateChainKey)

  companion object {
    /** The codec used by CertificateFetcherApi. */
    val codec: MessageCodec<Any?> by lazy {
      CertificateFetcherPigeonCodec()
    }
    /** Sets up an instance of `CertificateFetcherApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CertificateFetcherApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.CertificateFetcherApi.getCertificateChainSnapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as CertificateChainKey
            val wrapped: List<Any?> = try {
              listOf(api.getCertificateChainSnapshot(keyArg))
            } catch (exception: Throwable) {
              CertificateFetcherPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.CertificateFetcherApi.cancelCertificateChainForHost$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as CertificateChainKey
            val wrapped: List<Any?> = try {
              api.cancelCertificateChainForHost(keyArg)
              listOf(null)
            } catch (exception: Throwable) {
              CertificateFetcherPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
