// Autogenerated from Pigeon (v26.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length && a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) && _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

/// Result of a synchronous snapshot read; Dart polls until [success] or [failed].
enum CertificateChainSnapshotStatus {
  /// Native fetch in flight or not yet started for this key.
  pending,

  /// Terminal success; [certificates] is non-empty (DER base64).
  success,

  /// Terminal failure (timeout, empty chain, etc.); [certificates] is empty.
  failed,
}

/// Cache / single-flight key (no per-call id).
class CertificateChainKey {
  CertificateChainKey({required this.host, required this.port});

  String host;

  int port;

  List<Object?> _toList() {
    return <Object?>[host, port];
  }

  Object encode() {
    return _toList();
  }

  static CertificateChainKey decode(Object result) {
    result as List<Object?>;
    return CertificateChainKey(host: result[0]! as String, port: result[1]! as int);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CertificateChainKey || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class CertificateChainSnapshot {
  CertificateChainSnapshot({required this.status, required this.certificates});

  CertificateChainSnapshotStatus status;

  /// DER, base64. Non-empty only when [status] == [CertificateChainSnapshotStatus.success].
  List<String> certificates;

  List<Object?> _toList() {
    return <Object?>[status, certificates];
  }

  Object encode() {
    return _toList();
  }

  static CertificateChainSnapshot decode(Object result) {
    result as List<Object?>;
    return CertificateChainSnapshot(
      status: result[0]! as CertificateChainSnapshotStatus,
      certificates: (result[1] as List<Object?>?)!.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CertificateChainSnapshot || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is CertificateChainSnapshotStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is CertificateChainKey) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is CertificateChainSnapshot) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CertificateChainSnapshotStatus.values[value];
      case 130:
        return CertificateChainKey.decode(readValue(buffer)!);
      case 131:
        return CertificateChainSnapshot.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CertificateFetcherApi {
  /// Constructor for [CertificateFetcherApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CertificateFetcherApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Fast path: returns cached terminal state, [pending], or starts background fetch and returns [pending].
  Future<CertificateChainSnapshot> getCertificateChainSnapshot(CertificateChainKey key) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.personal_cloud_photos.CertificateFetcherApi.getCertificateChainSnapshot$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[key]);
    final List<Object?>? pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CertificateChainSnapshot?)!;
    }
  }

  /// Aborts in-flight fetch for [key] (e.g. when Dart stops polling early).
  Future<void> cancelCertificateChainForHost(CertificateChainKey key) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.personal_cloud_photos.CertificateFetcherApi.cancelCertificateChainForHost$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[key]);
    final List<Object?>? pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
