// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.seagate.curator.stxphotos.android.clipboard

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ClipboardMessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Represents a photo file that can be copied to clipboard
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ClipboardPhoto (
  val filePath: String,
  val fileName: String,
  val fileSize: Long,
  val mimeType: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ClipboardPhoto {
      val filePath = pigeonVar_list[0] as String
      val fileName = pigeonVar_list[1] as String
      val fileSize = pigeonVar_list[2] as Long
      val mimeType = pigeonVar_list[3] as String
      return ClipboardPhoto(filePath, fileName, fileSize, mimeType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      filePath,
      fileName,
      fileSize,
      mimeType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ClipboardPhoto) {
      return false
    }
    if (this === other) {
      return true
    }
    return ClipboardMessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Result of clipboard operations
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ClipboardResult (
  val success: Boolean,
  val error: String? = null,
  val photoCount: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ClipboardResult {
      val success = pigeonVar_list[0] as Boolean
      val error = pigeonVar_list[1] as String?
      val photoCount = pigeonVar_list[2] as Long
      return ClipboardResult(success, error, photoCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      error,
      photoCount,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ClipboardResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return ClipboardMessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class ClipboardMessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ClipboardPhoto.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ClipboardResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ClipboardPhoto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ClipboardResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeClipboardApi {
  /**
   * Copy photos to the system clipboard
   * Returns success status and any error message
   */
  fun copyPhotosToClipboard(filePaths: List<String>): ClipboardResult
  /**
   * Get photos from the system clipboard
   * Returns list of photo file paths if available
   */
  fun getPhotosFromClipboard(): List<String>
  /**
   * Check if there are photos in the clipboard
   * Returns true if photos are available
   */
  fun hasPhotosInClipboard(): Boolean
  /**
   * Get clipboard photo metadata
   * Returns list of photo information if available
   */
  fun getClipboardPhotoMetadata(): List<ClipboardPhoto>
  /**
   * Clear the system clipboard
   * Returns true if clipboard was cleared successfully
   */
  fun clearClipboard(): Boolean

  companion object {
    /** The codec used by NativeClipboardApi. */
    val codec: MessageCodec<Any?> by lazy {
      ClipboardMessagesPigeonCodec()
    }
    /** Sets up an instance of `NativeClipboardApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeClipboardApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.curator_photos_clipboard.NativeClipboardApi.copyPhotosToClipboard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filePathsArg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              listOf(api.copyPhotosToClipboard(filePathsArg))
            } catch (exception: Throwable) {
              ClipboardMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.curator_photos_clipboard.NativeClipboardApi.getPhotosFromClipboard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPhotosFromClipboard())
            } catch (exception: Throwable) {
              ClipboardMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.curator_photos_clipboard.NativeClipboardApi.hasPhotosInClipboard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hasPhotosInClipboard())
            } catch (exception: Throwable) {
              ClipboardMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.curator_photos_clipboard.NativeClipboardApi.getClipboardPhotoMetadata$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getClipboardPhotoMetadata())
            } catch (exception: Throwable) {
              ClipboardMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.curator_photos_clipboard.NativeClipboardApi.clearClipboard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.clearClipboard())
            } catch (exception: Throwable) {
              ClipboardMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
