// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.seagate.curator.stxphotos.android.networkmonitor

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NetworkMonitorPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class NativeTransportType(val raw: Int) {
  WIFI(0),
  CELLULAR(1),
  ETHERNET(2),
  VPN(3),
  OTHER(4);

  companion object {
    fun ofRaw(raw: Int): NativeTransportType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * OS-reported network status used by the network monitor for recovery and
 * toast decisions. A read-only side channel: it does not replace
 * [ConnectivityApi], which stays untouched for backup checks.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeNetworkStatus (
  val hasTransport: Boolean,
  val transports: List<NativeTransportType>,
  /**
   * Whether the OS considers the network to actually have internet access.
   * Android: NET_CAPABILITY_VALIDATED (system-side captive portal / internet
   * validation). iOS has no public equivalent, so it reports null when a
   * route exists and false when there is no route at all.
   */
  val internetValidated: Boolean? = null,
  val isExpensive: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeNetworkStatus {
      val hasTransport = pigeonVar_list[0] as Boolean
      val transports = pigeonVar_list[1] as List<NativeTransportType>
      val internetValidated = pigeonVar_list[2] as Boolean?
      val isExpensive = pigeonVar_list[3] as Boolean
      return NativeNetworkStatus(hasTransport, transports, internetValidated, isExpensive)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      hasTransport,
      transports,
      internetValidated,
      isExpensive,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeNetworkStatus) {
      return false
    }
    if (this === other) {
      return true
    }
    return NetworkMonitorPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class NetworkMonitorPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeTransportType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeNetworkStatus.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeTransportType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is NativeNetworkStatus -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NetworkMonitorApi {
  fun getCurrentStatus(): NativeNetworkStatus
  fun startObserving()
  fun stopObserving()

  companion object {
    /** The codec used by NetworkMonitorApi. */
    val codec: MessageCodec<Any?> by lazy {
      NetworkMonitorPigeonCodec()
    }
    /** Sets up an instance of `NetworkMonitorApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NetworkMonitorApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.NetworkMonitorApi.getCurrentStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCurrentStatus())
            } catch (exception: Throwable) {
              NetworkMonitorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.NetworkMonitorApi.startObserving$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startObserving()
              listOf(null)
            } catch (exception: Throwable) {
              NetworkMonitorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.NetworkMonitorApi.stopObserving$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopObserving()
              listOf(null)
            } catch (exception: Throwable) {
              NetworkMonitorPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class NetworkMonitorEvents(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by NetworkMonitorEvents. */
    val codec: MessageCodec<Any?> by lazy {
      NetworkMonitorPigeonCodec()
    }
  }
  fun onStatusChanged(statusArg: NativeNetworkStatus, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.personal_cloud_photos.NetworkMonitorEvents.onStatusChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NetworkMonitorPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
