// Autogenerated from Pigeon (v26.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.seagate.curator.stxphotos.android.accountmanager

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AccountManagerPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class Account (
  val name: String,
  val type: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Account {
      val name = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as String
      return Account(name, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      type,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Account) {
      return false
    }
    if (this === other) {
      return true
    }
    return AccountManagerPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UserData (
  val key: String,
  val value: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UserData {
      val key = pigeonVar_list[0] as String
      val value = pigeonVar_list[1] as String
      return UserData(key, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      key,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is UserData) {
      return false
    }
    if (this === other) {
      return true
    }
    return AccountManagerPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class AccountManagerPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Account.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UserData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is Account -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is UserData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AccountManagerApi {
  fun addAccount(account: Account, password: String, callback: (Result<Account>) -> Unit)
  fun getAccounts(callback: (Result<List<Account>>) -> Unit)
  fun removeAccount(account: Account, callback: (Result<Boolean>) -> Unit)
  fun hasAccount(accountName: String, accountType: String, callback: (Result<Boolean>) -> Unit)
  fun setUserData(account: Account, userData: Map<String, String?>, callback: (Result<Boolean>) -> Unit)
  fun getUserData(account: Account, keys: List<String>, callback: (Result<Map<String, String?>>) -> Unit)
  fun getPassword(account: Account, callback: (Result<String?>) -> Unit)
  fun setPassword(account: Account, password: String?, callback: (Result<Boolean>) -> Unit)
  fun removeUserData(account: Account, keys: List<String>, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by AccountManagerApi. */
    val codec: MessageCodec<Any?> by lazy {
      AccountManagerPigeonCodec()
    }
    /** Sets up an instance of `AccountManagerApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AccountManagerApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.AccountManagerApi.addAccount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as Account
            val passwordArg = args[1] as String
            api.addAccount(accountArg, passwordArg) { result: Result<Account> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.AccountManagerApi.getAccounts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAccounts{ result: Result<List<Account>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.AccountManagerApi.removeAccount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as Account
            api.removeAccount(accountArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.AccountManagerApi.hasAccount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountNameArg = args[0] as String
            val accountTypeArg = args[1] as String
            api.hasAccount(accountNameArg, accountTypeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.AccountManagerApi.setUserData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as Account
            val userDataArg = args[1] as Map<String, String?>
            api.setUserData(accountArg, userDataArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.AccountManagerApi.getUserData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as Account
            val keysArg = args[1] as List<String>
            api.getUserData(accountArg, keysArg) { result: Result<Map<String, String?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.AccountManagerApi.getPassword$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as Account
            api.getPassword(accountArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.AccountManagerApi.setPassword$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as Account
            val passwordArg = args[1] as String?
            api.setPassword(accountArg, passwordArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personal_cloud_photos.AccountManagerApi.removeUserData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as Account
            val keysArg = args[1] as List<String>
            api.removeUserData(accountArg, keysArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AccountManagerPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AccountManagerPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
