// Autogenerated from Pigeon (v26.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.seagate.curator.stxphotos.android.update

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object UpdateApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeUpdateInfo (
  val version: String,
  val url: String,
  val changelog: String? = null,
  val minSupportedVersion: String? = null,
  val sha256: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeUpdateInfo {
      val version = pigeonVar_list[0] as String
      val url = pigeonVar_list[1] as String
      val changelog = pigeonVar_list[2] as String?
      val minSupportedVersion = pigeonVar_list[3] as String?
      val sha256 = pigeonVar_list[4] as String?
      return NativeUpdateInfo(version, url, changelog, minSupportedVersion, sha256)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      version,
      url,
      changelog,
      minSupportedVersion,
      sha256,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeUpdateInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return UpdateApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DownloadProgress (
  val percent: Long,
  val bytesDownloaded: Long,
  val totalBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DownloadProgress {
      val percent = pigeonVar_list[0] as Long
      val bytesDownloaded = pigeonVar_list[1] as Long
      val totalBytes = pigeonVar_list[2] as Long
      return DownloadProgress(percent, bytesDownloaded, totalBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      percent,
      bytesDownloaded,
      totalBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DownloadProgress) {
      return false
    }
    if (this === other) {
      return true
    }
    return UpdateApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InstallResult (
  val success: Boolean,
  val errorCode: String? = null,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InstallResult {
      val success = pigeonVar_list[0] as Boolean
      val errorCode = pigeonVar_list[1] as String?
      val message = pigeonVar_list[2] as String?
      return InstallResult(success, errorCode, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      errorCode,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is InstallResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return UpdateApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class UpdateApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeUpdateInfo.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DownloadProgress.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InstallResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeUpdateInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is DownloadProgress -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is InstallResult -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface UpdateApi {
  fun fetchLatestUpdate(url: String): NativeUpdateInfo?
  fun startDownload(version: String, url: String, sha256: String?)
  fun installDownloadedUpdate(): InstallResult

  companion object {
    /** The codec used by UpdateApi. */
    val codec: MessageCodec<Any?> by lazy {
      UpdateApiPigeonCodec()
    }
    /** Sets up an instance of `UpdateApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: UpdateApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.curator_photos.UpdateApi.fetchLatestUpdate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.fetchLatestUpdate(urlArg))
            } catch (exception: Throwable) {
              UpdateApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.curator_photos.UpdateApi.startDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val versionArg = args[0] as String
            val urlArg = args[1] as String
            val sha256Arg = args[2] as String?
            val wrapped: List<Any?> = try {
              api.startDownload(versionArg, urlArg, sha256Arg)
              listOf(null)
            } catch (exception: Throwable) {
              UpdateApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.curator_photos.UpdateApi.installDownloadedUpdate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.installDownloadedUpdate())
            } catch (exception: Throwable) {
              UpdateApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class UpdateCallbacks(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by UpdateCallbacks. */
    val codec: MessageCodec<Any?> by lazy {
      UpdateApiPigeonCodec()
    }
  }
  fun onDownloadProgress(progressArg: DownloadProgress, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.curator_photos.UpdateCallbacks.onDownloadProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(UpdateApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onDownloadError(messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.curator_photos.UpdateCallbacks.onDownloadError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(UpdateApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onDownloadCompleted(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.curator_photos.UpdateCallbacks.onDownloadCompleted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(UpdateApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
